### ISSUE TITLE
Consistent with The Target Paper

### ISSUE THREAD

**Issue by ghost** [TRSasasusu/SpikingMoYF#2]
The way input spikes are generated is inconsistent with the description in the paper **Training Deep Spiking Neural Networks Using Backpropagation**.

**Comment by TRSasasusu** [comment]
Thank you for making an issue, but now I think this kind of SNN is not essential to real neuroscience, so I have no plan to fix it.

(However, I would like to know what is inconsistent with the description about input spikes generation. Could you tell me the detail?)

**Comment by ghost** [comment]
I totally agree that neuron parameters used in the paper are not realistic.

The author creates 784 Poisson spiking neurons; each of which corresponds to an individual pixel of MNIST sample. Pixel intensity (0-255) is scaled and set to be the firing rate of the Poisson spiking neurons. Thus, at any time instance, chance of firing depends on scaled value of pixel intensity.

**Comment by TRSasasusu** [comment]
Thank you! The link of this issue has just been placed on the top of README.
